#!/usr/bin/env bash
set -euo pipefail

# Wrapper script: run NSW electricity pipeline with case retrieval ON.
# You can still override any of these via environment variables.
export CASE_RETRIEVAL_ENABLE="${CASE_RETRIEVAL_ENABLE:-1}"
export CASE_RETRIEVAL_TOPK="${CASE_RETRIEVAL_TOPK:-5}"
export CASE_RETRIEVAL_MODE="${CASE_RETRIEVAL_MODE:-price_event}"          # off | price | price_event
export CASE_RETRIEVAL_ALPHA_PRICE="${CASE_RETRIEVAL_ALPHA_PRICE:-0.85}"
export CASE_RETRIEVAL_ALPHA_EVENT="${CASE_RETRIEVAL_ALPHA_EVENT:-0.15}"
export CASE_RETRIEVAL_MIN_TOP_SCORE="${CASE_RETRIEVAL_MIN_TOP_SCORE:-0.12}"
export CASE_RETRIEVAL_MIN_CANDIDATES="${CASE_RETRIEVAL_MIN_CANDIDATES:-2}"
export CASE_RETRIEVAL_MIN_DIR_AGREE="${CASE_RETRIEVAL_MIN_DIR_AGREE:-0.45}"
export CASE_RETRIEVAL_MAX_EVENT_MISMATCH="${CASE_RETRIEVAL_MAX_EVENT_MISMATCH:-0.80}"
export CASE_RETRIEVAL_FEATURE_DIM="${CASE_RETRIEVAL_FEATURE_DIM:-12}"
export CASE_RETRIEVAL_GATE_ONLY="${CASE_RETRIEVAL_GATE_ONLY:-0}"
export CASE_RETRIEVAL_RUN_ABLATIONS="${CASE_RETRIEVAL_RUN_ABLATIONS:-1}"
export CASE_RETRIEVAL_ABLATION_SPLIT="${CASE_RETRIEVAL_ABLATION_SPLIT:-val}"  # val | test | both

bash "$(dirname "$0")/nswelecload_new_3.sh" "$@"
